<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <SpaRoot>..\IMuDB.Client</SpaRoot>
	  <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
	  <SpaProxyServerUrl>https://localhost:3000</SpaProxyServerUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IMuDB.Domain\IMuDB.Domain.csproj" />
    <ProjectReference Include="..\IMuDB.Infrastructure.Services\IMuDB.Infrastructure.Services.csproj" />
    <ProjectReference Include="..\IMuDB.Infrastructure\IMuDB.Infrastructure.csproj" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\IMuDB.Client\imudb.client.esproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

</Project>
