// <auto-generated />
using System;
using IMuDB.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMuDB.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250815194956_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActEntityMusicianEntity", b =>
                {
                    b.Property<string>("ActsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MusiciansId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ActsId", "MusiciansId");

                    b.HasIndex("MusiciansId");

                    b.ToTable("ActEntityMusicianEntity");
                });

            modelBuilder.Entity("MusicianEntityInstrumentEntity", b =>
                {
                    b.Property<string>("MusiciansId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InstrumentsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MusiciansId", "InstrumentsId");

                    b.HasIndex("InstrumentsId");

                    b.ToTable("MusicianEntityInstrumentEntity");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Acts.ActEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Albums.AlbumEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Musicians.MusicianEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Instruments.InstrumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Songs.SongEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlbumId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Track")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("ActEntityMusicianEntity", b =>
                {
                    b.HasOne("IMuDB.Domain.Entities.Acts.ActEntity", null)
                        .WithMany()
                        .HasForeignKey("ActsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMuDB.Domain.Entities.Musicians.MusicianEntity", null)
                        .WithMany()
                        .HasForeignKey("MusiciansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicianEntityInstrumentEntity", b =>
                {
                    b.HasOne("IMuDB.Domain.Entities.Musicians.MusicianEntity", null)
                        .WithMany()
                        .HasForeignKey("MusiciansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMuDB.Domain.Entities.Instruments.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Albums.AlbumEntity", b =>
                {
                    b.HasOne("IMuDB.Domain.Entities.Acts.ActEntity", "Act")
                        .WithMany("Albums")
                        .HasForeignKey("ActId");

                    b.Navigation("Act");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Songs.SongEntity", b =>
                {
                    b.HasOne("IMuDB.Domain.Entities.Acts.ActEntity", "Act")
                        .WithMany()
                        .HasForeignKey("ActId");

                    b.HasOne("IMuDB.Domain.Entities.Albums.AlbumEntity", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId");

                    b.Navigation("Act");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Acts.ActEntity", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("IMuDB.Domain.Entities.Albums.AlbumEntity", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
